- name: Setting up
  hosts: worker1
  remote_user: labsuser
  tasks:
      - name: Install Git & Maven
        become: true
        become_user: root
        become_method: sudo
        apt:
            name:
                - git
                - maven
            state: present

      - name: Create directory for file
        file:
            path: "/home/labsuser/tests/ansible-examples"
            state: directory
            recurse: yes
            owner: labsuser
            group: labsuser
            mode: 0755

      - name: Clone addressbook github repo
        ansible.builtin.git:
            repo: https://github.com/AhmadMazaal/addressbook.git
            dest: /home/labsuser/tests/ansible-examples

      - name: Package the project
        shell:
            cmd: mvn package
            chdir: /home/labsuser/tests/ansible-examples

      - name: Create a Tomcat User

        user:
            name: tomcat
      - name: Create a Tomcat Group
        become: true
        become_user: root
        become_method: sudo
        group:
            name: tomcat

      - name: Create a Tomcat directory
        become: true
        become_user: root
        become_method: sudo
        file:
            path: /opt/tomcat
            owner: tomcat
            group: tomcat
            mode: 0755
            recurse: yes

      - name: download & unarchive Tomcat
        unarchive:
            mode: 0755
            owner: tomcat
            group: tomcat
            src: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.71/bin/apache-tomcat-9.0.71.tar.gz
            dest: /opt/tomcat
            remote_src: yes
            extra_opts: [--strip-components=1]

      - name: Copy Tomcat service from local to remote
        become: true
        become_user: root
        become_method: sudo
        copy:
            src: tomcat.service
            dest: /etc/systemd/system/
            mode: 0755

      - name: Start and enable Tomcat on sever
        become: true
        become_user: root
        become_method: sudo
        systemd:
            name: tomcat
            state: restarted
            enabled: yes
            daemon_reload: true

      - name: Copy War file to webapps in Tomcat
        become: true
        become_user: root
        become_method: sudo
        copy:
            owner: tomcat
            group: tomcat
            src: /home/labsuser/tests/ansible-examples/target/addressbook-2.0.war
            dest: /opt/tomcat/webapps
            remote_src: yes
            mode: 0755
